# Install Python, pip, and virtualenv.
---
- name: install python from apt
  apt: pkg={{ item }} state=installed
  sudo: yes
  with_items:
  - python-dev
  - python3-dev
  - python-pip
  - python3-pip
  - cowsay
  - unzip
  - zip
  - libffi-dev

- name: install global packages
  pip: name={{ item }} state=latest
  sudo: yes
  with_items:
  - virtualenv
  - ansible
